### Library

In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold

from collections import Counter

### Train & Validation Set 나누기

In [4]:
train_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DACON/Fashion_MNIST/data/train.csv')

In [5]:
# train_data 갯수만큼 1을 담는 넘파이 배열 X, label을 넘파이 배열로 바꾼 y
X = np.ones((len(train_data),1)) 
y = np.array(train_data['label'])

# n_splits = fold 갯수
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# 나눠준 fold를 확인해보고 csv로 저장
for fold_ind, (train_idx, val_idx) in enumerate(cv.split(X,y)):  
    print(f"TRAIN {fold_ind}:", [train_idx])
    print(" ", y[train_idx])
    train_data.loc[train_idx].to_csv(f'/content/drive/MyDrive/Colab Notebooks/DACON/Fashion_MNIST/data/train{fold_ind}.csv', index = None)
    print(f" TEST {fold_ind}:", [val_idx])
    print(" ", y[val_idx])
    train_data.loc[val_idx].to_csv(f'/content/drive/MyDrive/Colab Notebooks/DACON/Fashion_MNIST/data/val{fold_ind}.csv', index = None)

TRAIN 0: [array([    0,     1,     2, ..., 59997, 59998, 59999])]
  [2 9 6 ... 8 8 7]
 TEST 0: [array([    4,     5,    15, ..., 59991, 59992, 59993])]
  [3 4 2 ... 5 5 2]
TRAIN 1: [array([    1,     2,     3, ..., 59991, 59992, 59993])]
  [9 6 0 ... 5 5 2]
 TEST 1: [array([    0,     6,     8, ..., 59997, 59998, 59999])]
  [2 4 4 ... 8 8 7]
TRAIN 2: [array([    0,     1,     3, ..., 59997, 59998, 59999])]
  [2 9 0 ... 8 8 7]
 TEST 2: [array([    2,    12,    16, ..., 59978, 59986, 59990])]
  [6 9 9 ... 6 6 0]
TRAIN 3: [array([    0,     2,     4, ..., 59997, 59998, 59999])]
  [2 6 3 ... 8 8 7]
 TEST 3: [array([    1,     3,    14, ..., 59982, 59983, 59985])]
  [9 0 2 ... 5 5 6]
TRAIN 4: [array([    0,     1,     2, ..., 59997, 59998, 59999])]
  [2 9 6 ... 8 8 7]
 TEST 4: [array([    7,     9,    10, ..., 59981, 59984, 59987])]
  [5 8 0 ... 5 7 5]

In [6]:
# label 별 갯수 세는 함수
def get_counts(y): 
    y_count = Counter(y)
    return [f'{y_count[i]}' for i in range(np.max(y) +1)]


# train_data의 총 label 별 데이터 개수 담아주기
counts = [get_counts(y)]
index = ['training set']

# fold 별로 클래스 비율이 어떻게 나뉘었는지 확인하기
for fold_ind, (train_idx, val_idx) in enumerate(cv.split(X,y)): 
    train_y, val_y = y[train_idx], y[val_idx]

    counts.append(get_counts(train_y)) 
    counts.append(get_counts(val_y))
    index.append(f'train - fold{fold_ind}')
    index.append(f'val - fold{fold_ind}')

# DataFrame으로 만들어 확인 
pd.DataFrame(counts, index=index, columns = [i for i in range(10)])

                  0     1     2     3     4     5     6     7     8     9
training set   6000  6000  6000  6000  6000  6000  6000  6000  6000  6000
train - fold0  4800  4800  4800  4800  4800  4800  4800  4800  4800  4800
val - fold0    1200  1200  1200  1200  1200  1200  1200  1200  1200  1200
train - fold1  4800  4800  4800  4800  4800  4800  4800  4800  4800  4800
val - fold1    1200  1200  1200  1200  1200  1200  1200  1200  1200  1200
train - fold2  4800  4800  4800  4800  4800  4800  4800  4800  4800  4800
val - fold2    1200  1200  1200  1200  1200  1200  1200  1200  1200  1200
train - fold3  4800  4800  4800  4800  4800  4800  4800  4800  4800  4800
val - fold3    1200  1200  1200  1200  1200  1200  1200  1200  1200  1200
train - fold4  4800  4800  4800  4800  4800  4800  4800  4800  4800  4800
val - fold4    1200  1200  1200  1200  1200  1200  1200  1200  1200  1200